name: Create or Update Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Zip project
      run: zip -r mmg-checkout-payment.zip . -x "*.git*"

    - name: Create or Update Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./mmg-checkout-payment.zip
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false