name: Create or Update Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Update version in main.php
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config --local user.email "carl@kalpa.dev"
        git config --local user.name "Carl Handy"
        git fetch --all
        git checkout main
        git pull origin main
        chmod +x .github/scripts/update-version.sh
        ./.github/scripts/update-version.sh
        git push origin main

  build:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest changes
      run: |
        git fetch --all
        git checkout main
        git pull origin main

    - name: Zip project
      run: zip -r mmg-checkout-payment.zip . -x "*.git*" -x "tests/*" -x "bin/*" -x "composer.json" -x "phpunit.xml" -x "README.md" -x "*.DS_Store" -x "build-phar.sh"

    - name: Get Release
      id: get_release
      run: |
        release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}" \
          | jq -r '.id')
        upload_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/$release_id" \
          | jq -r '.upload_url')
        echo "release_id=$release_id" >> $GITHUB_OUTPUT
        echo "upload_url=$upload_url" >> $GITHUB_OUTPUT

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./mmg-checkout-payment.zip
        asset_name: mmg-checkout-payment.zip
        asset_content_type: application/zip