name: Update Version

on:
  push:
    tags:
      - 'v*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update version in main.php
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "carl@kalpa.dev"
        git config --local user.name "Carl Handy"
        chmod +x .github/scripts/update-version.sh
        .github/scripts/update-version.sh